### ISSUE TITLE
Browser title isn't cleared when queue finishes

### ISSUE THREAD

**Issue by nixme** [nixme/warble#11]
When the queue finishes and there are no songs to play, the browser title still has the name of the last song. Should clear it out and just say "Warble"

**Comment by arbales** [comment]
This is fixed in my branch.

A more robust solution for titling though, would be found in using the history api, and implementing a `#historyState` method on controllers so that when history is saved, a page title is also saved in the hash, and then can be recalled/set whenever history changes. I tried to just add a call into the controller that would set the page title, but it seems that there is some racing there that makes the page titles reset each other as the page loads.

**Comment by arbales** [comment]
Actually, integrating History.js would be the best option.

**Comment by nixme** [comment]
The next version of Backbone.js should have optional HTML5 pushstate support. There are already forks with history.js included, but I'd rather put it off until Backbone has it proper.
